#!/usr/bin/env python3
"""Regenerate the CPU64::step() opcode dispatch jump table.

step()'s single-byte opcode handling is a linear if-cascade; a native profile
showed the compare chain costing a meaningful slice of interpreter time. This
tool inserts (or refreshes) a `switch (op)` prologue that jumps every opcode
value straight to the FIRST if-block whose condition could possibly match it.

Semantics are provably unchanged: the target block's own condition still
evaluates (so secondary terms like REX bits or the 0F sub-byte still fall
through to later blocks exactly as before); only compares that can never
match the opcode value are skipped. Opcode values no block can match jump to
the existing `unhandled:` tail.

Run from the repo root after adding/reordering opcode blocks in step():
    python3 tools/gen_dispatch64.py
Then rebuild + `--x64-selftest` (must stay 234/234).
"""
import re
import sys
from collections import defaultdict

PATH = 'source/emulation/cpu/cpu64.cpp'
GEN_BEGIN = '    // ---- Dispatch jump table ----'
GEN_END_MARK = '    // ---- Single-byte opcodes ----'


def strip_generated(src):
    out = []
    i = 0
    while i < len(src):
        line = src[i]
        if line == GEN_BEGIN:
            while src[i] != GEN_END_MARK:
                i += 1
            continue  # drops everything up to (not incl.) the section marker
        if re.match(r'^dsp_\d+:$', line):
            i += 1
            continue
        out.append(line)
        i += 1
    return out


def could_match(cond, v):
    c = cond
    c = re.sub(r'fetchByte\([^)]*\)\s*==\s*0x[0-9A-Fa-f]+', ' (1) ', c)
    c = re.sub(r'p\.rep\s*==\s*0x[0-9A-Fa-f]+', ' (1) ', c)
    c = re.sub(r'!\(p\.rex & 0x0?[0-9A-Fa-f]+\)', ' (1) ', c)
    c = re.sub(r'\(p\.rex & 0x0?[0-9A-Fa-f]+\)', ' (1) ', c)
    c = re.sub(r'\bp\.rex\b', ' (1) ', c)
    c = c.replace('&&', ' and ').replace('||', ' or ')
    c = re.sub(r'!(?!=)', ' not ', c)
    c = re.sub(r'\bop\b', f'({v})', c)
    return bool(eval(c))  # trusted input: our own source file


def main():
    src = open(PATH).read().split('\n')
    src = strip_generated(src)

    start = next(i for i, l in enumerate(src) if l.startswith('U32 CPU64::step()'))
    end = next(i for i in range(start + 1, len(src)) if re.match(r'^[A-Za-z].*CPU64::', src[i]))
    mark = next(i for i in range(start, end) if GEN_END_MARK == src[i])
    unh = next(i for i in range(start, end) if src[i].startswith('unhandled:'))

    # Collect top-level if-blocks between the marker and the unhandled tail.
    blocks = []
    i = mark + 1
    while i < unh:
        line = src[i]
        if re.match(r'^    if \(', line):
            buf = line[len('    if '):]
            j = i
            while True:
                depth_par = 0
                condchars = []
                done = False
                for k, ch in enumerate(buf):
                    if ch == '(':
                        depth_par += 1
                    elif ch == ')':
                        depth_par -= 1
                        if depth_par == 0:
                            cond = ''.join(condchars[1:])
                            rest = buf[k + 1:]
                            done = True
                            break
                    condchars.append(ch)
                if done:
                    break
                j += 1
                buf += ' ' + src[j].strip()
            blocks.append((i, ' '.join(cond.split())))
            d = rest.count('{') - rest.count('}')
            while d > 0:
                j += 1
                d += src[j].count('{') - src[j].count('}')
            i = j + 1
            continue
        stripped = line.strip()
        if stripped and not stripped.startswith('//'):
            sys.exit(f"unexpected statement at cascade level, L{i+1}: {line!r}")
        i += 1

    target = {}
    for v in range(256):
        t = -1
        for bi, (li, cond) in enumerate(blocks):
            if could_match(cond, v):
                t = bi
                break
        target[v] = t

    used = sorted(set(v for v in target.values() if v >= 0))
    groups = defaultdict(list)
    for v in range(256):
        groups[target[v]].append(v)

    sw = [GEN_BEGIN]
    sw += [
        '    // Generated by tools/gen_dispatch64.py from the if-cascade below: every',
        '    // opcode value jumps to the FIRST block whose condition could possibly',
        '    // match it (conditions with non-op terms still evaluate at the target and',
        '    // fall through to later blocks exactly as before — only the provably',
        '    // non-matching compares above the target are skipped). A native profile',
        '    // had 34% of interpreter time in step(); the linear compare chain was a',
        '    // large slice of that. Ops no block can match go straight to `unhandled`.',
        '    // REGENERATE (do not hand-edit) after adding/reordering opcode blocks:',
        '    //   python3 tools/gen_dispatch64.py',
        '    switch (op) {',
    ]
    for t in used + [-1]:
        ops = groups.get(t, [])
        if not ops:
            continue
        label = f'dsp_{t}' if t >= 0 else 'unhandled'
        line = '        '
        for v in ops:
            line += f'case {v:#04x}: '
            if len(line) > 90:
                sw.append(line)
                line = '        '
        line += f'goto {label};'
        sw.append(line)
    sw += ['    }', '']

    out = src[:mark] + sw
    label_at = {blocks[t][0]: f'dsp_{t}:' for t in used}
    for idx in range(mark, len(src)):
        if idx in label_at:
            out.append(label_at[idx])
        out.append(src[idx])
    open(PATH, 'w').write('\n'.join(out))
    print(f"regenerated: {len(blocks)} blocks, {len(used)} labels, "
          f"{sum(1 for t in target.values() if t < 0)} ops -> unhandled")


if __name__ == '__main__':
    main()
